name: workflow1
on:
  workflow_dispatch
jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
      - run: pwd
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
         node-version: '20.x'
      - run: npm -v
